### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by LoriRongrong** [UCSD-AI4H/CERT#2]
After creating "augment.csv" file, I used the command "python MOCO.py" and had the following error. I am not so sure if this is due to an update in progress. Thanks.

> Traceback (most recent call last):
  File "MOCO.py", line 405, in <module>
    main()
  File "MOCO.py", line 134, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "MOCO.py", line 263, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, args, losslist)
  File "MOCO.py", line 309, in train
    output, target = model(sen_q=sen1, sen_k=sen2, mask_q=mask1, mask_k=mask2)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/CERT-master/moco/builder.py", line 142, in forward
    sen_k, idx_unshuffle = self._batch_shuffle_ddp(sen_k)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/content/CERT-master/moco/builder.py", line 85, in _batch_shuffle_ddp
    x_gather = concat_all_gather(x)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/content/CERT-master/moco/builder.py", line 174, in concat_all_gather
    for _ in range(torch.distributed.get_world_size())]
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 582, in get_world_size
    return _get_group_size(group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 196, in _get_group_size
    _check_default_pg()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 187, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

**Comment by JiayuanDing100** [comment]
Hi,

Before update, moco task training is not supported multiple GPUs training, we have to specify the only one GPU for moco task training. But it support multiple GPUs training after update in MOCO.py.

I wanna confirm whether you are using current MOCO.py codebase.

**Comment by LoriRongrong** [comment]
Yes, I just downloaded the most recent code as a zip file and tried to run the updated code.

**Comment by JiayuanDing100** [comment]
resolved
